spring.profiles.active: ${daemon.mode:dev}

logging.config: classpath:config/logback.xml

---

spring.profiles: client

client.daemon.port: 8080

---

spring.profiles: server

server.daemon.port: 9090

---

spring.profiles: dev
spring.profiles.include:
  - client
  - server
server.daemon.host: 127.0.0.1

---

spring.profiles: prod

logging.file: great-free-will.log

---

spring.profiles: clientd
spring.profiles.include:
  - client
  - prod

---

spring.profiles: serverd
spring.profiles.include:
  - server
  - prod

