spring.profiles.active: ${daemon.mode:dev}

logging.config: classpath:config/logback.xml
logging.level.io.netty.handler.logging.LoggingHandler: DEBUG

---

spring.profiles: client

---

spring.profiles: server

---

spring.profiles: dev
spring.profiles.include:
  - client
  - server
client.daemon.port: 8080
server.daemon.port: 9090
server.daemon.host: 127.0.0.1
daemon.secret: keepifsecret

---

spring.profiles: prod

logging.file: great-free-will.log
logging.level.io.netty.handler.logging.LoggingHandler: INFO

---

spring.profiles: clientd
spring.profiles.include:
  - client
  - prod

---

spring.profiles: serverd
spring.profiles.include:
  - server
  - prod

